### ISSUE TITLE
Isolate search to a specific Jira ticket

### ISSUE THREAD

**Issue by bradyclifford** [im-open/verify-fields-on-jira-task#3]
How do we isolate and verify fields on a specific Jira Issue (ticket)?

@JosephDSchwartz

**Comment by JosephDSchwartz** [comment]
You can use the `project-names-to-search`, `issue-types-to-search`, `search-field-id`, and `search-value` parameters to find the ticket you want. For instance, the use case behind the creation of this action was searching for a deployment task with a specific version number in the "Proposed Build" field.

**Comment by bradyclifford** [comment]
I am wanting to search by ticket number, like `WE-1234`.  I want to verify that a specific ticket number has the properties desired.  How do I do that?

`issue-types-to-search` seems to be asking for issue type, not issue key.

**Comment by JosephDSchwartz** [comment]
There isn't a way to search by the issue key like you can in https://github.com/im-open/transition-jira-tasks-by-query. This action could be modified to do that, but that's not a current capability.
